name: Deploy::CDN

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: '是否使用缓存'
        required: true
        default: 'true'
    #  push:
    #    tags:
    #      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '*.md'
      - '*.editorconfig'
      - '*.gitignore'
env:
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
  QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
  QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
  QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: npm run build:prod.cdn
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          USE_LOG: false
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ env.REMOTE_HOST }}
          REMOTE_USER: ${{ env.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ env.SERVER_SSH_KEY }}
          TARGET: ${{ env.REMOTE_TARGET }}
          SOURCE: "dist/"
          EXCLUDE: "/dist/, /node_modules/"
      - uses: hocgin/action-qiniu-upload@master
        with:
          access_key: ${{ env.QINIU_ACCESS_KEY }}
          secret_key: ${{ env.QINIU_SECRET_KEY }}
          bucket: ${{ env.QINIU_BUCKET }}
          source_dir: 'dist'
          dest_dir: ${{github.event.repository.name}}
          ignore_source_map: true
          exclude: "index.html"
          overwrite: true
